- Arduino_package/hardware/platform.txt
Update and enabled "export compiled binary" and tested working on Windows and Linux
> Enabled "export compiled binary" on all OS

- Arduino_package/hardware/libraries/WS2812B/WS2812B.cpp
- Arduino_package/hardware/libraries/WS2812B/WS2812B.h
- Arduino_package/hardware/libraries/WS2812B/examples/WS2812B_Basics/WS2812B_Basics.ino
- Arduino_package/hardware/libraries/WS2812B/examples/WS2812B_Patterns/WS2812B_Patterns.ino
- Arduino_package/hardware/libraries/WS2812B/keywords.txt
- Arduino_package/hardware/libraries/WS2812B/library.properties
-Added
- Support for WS2812B LED using SPI peripheral
- WS2812B class
- Examples for WS2812B_Basics and WS2812B_Patterns
> Add WS2812B Library

- Arduino_package/hardware/libraries/GPIO/examples/DHT_Tester/DHT_Tester.ino
Update the comment section to advise the user that a 1K resistor is recommended for more accurate readings.
> Update DHT_Tester.ino comment section

- Arduino_package/hardware/libraries/Analog/examples/ServoSweep/ServoSweep.ino
- Arduino_package/hardware/libraries/Analog/examples/TonePlayMelody/TonePlayMelody.ino
- Arduino_package/hardware/libraries/IRDevice/examples/IRRecvNEC/IRRecvNEC.ino
- Arduino_package/hardware/libraries/IRDevice/examples/IRSendNEC/IRSendNEC.ino
- Arduino_package/hardware/libraries/IRDevice/examples/IRSendRAW/IRSendRAW.ino
- Arduino_package/hardware/libraries/IRDevice/examples/IRSendSONY/IRSendSONY.ino
- Arduino_package/hardware/libraries/MQTTClient/examples/LASS_Basic/LASS_Basic.ino
- Arduino_package/hardware/libraries/SoftwareSerial/examples/Adafruit_GPS_parsing/Adafruit_GPS_parsing.ino
- Arduino_package/hardware/libraries/SoftwareSerial/examples/PMS3003_AirQuality/PMS3003_AirQuality.ino
- Arduino_package/hardware/libraries/SoftwareSerial/examples/SoftwareSerial_Basic/SoftwareSerial_Basic.ino
- Arduino_package/hardware/libraries/SoftwareSerial/examples/SoftwareSerial_DetailSetting/SoftwareSerial_DetailSetting.ino
- Arduino_package/hardware/libraries/SoftwareSerial/examples/SoftwareSerial_IRQ_Callback/SoftwareSerial_IRQ_Callback.ino
- Arduino_package/hardware/libraries/Wire/src/Wire.cpp
- Arduino_package/hardware/variants/awcu488_thingplus/variant.h
- Arduino_package/hardware/variants/rtl8722dm_mini/variant.cpp
- Arduino_package/hardware/variants/rtl8722dm_mini/variant.h
- Added **RTL8721DM pin macro** into:
- `ServoSweep.ino  `
- `TonePlayMelody.ino`
- `IRRecvNEC.ino`
- `IRSendNEC.ino`
- `IRSendRaw.ino`
- `IRSendSONY.ino`
- `LASS_Basic.ino`
- `Adafruit_GPS_Parsing.ino`
- `PMS3003_AirQuality.ino`
- `SoftwareSerial_Basic.ino`
- `SoftwareSerial_DetailSettings.ino`
- `SoftwareSerial_IRQ_Callback.ino`
- Update AMB23 variant.h and variant.cpp
- Update awcu488_thingplus variant.h
> Updates for compatibility

- Arduino_package/hardware/libraries/Wire/examples/I2C_Scanner/I2C_Scanner.ino
- Add I2C_scanner example into Wire Library
> Add I2C_Scanner example in Wire

- Arduino_package/hardware/libraries/SPI/examples/ILI9341_TFT_LCD_PM2.5/ILI9341_TFT_LCD_PM2.5.ino
- Arduino_package/hardware/libraries/SPI/examples/ILI9341_TFT_LCD_basic/ILI9341_TFT_LCD_basic.ino
- Arduino_package/hardware/libraries/SPI/src/SPI.cpp
- Arduino_package/hardware/libraries/SPI/src/SPI.h
- README.md
- Update SPI LCD examples to solve the conflicted GPIO pin and the wrong SPI init sequence issue
- Update certain SPI Class APIs to prevent system hang issue
- Fix typo
> [SPI] Fix SPI LCD example not working issue

- Arduino_package/hardware/cores/ambd/Arduino.h
- Fix compilation error with issue (#131)
- Update Arduino.h to include dtostrf and itoa libraries
Verification:
- Tested against WiFiSSLClient and Blink example and passed
> Fix issue (#131) and improve SDK compatibility with 3rd party libs

- Arduino_package/hardware/libraries/SPI/src/SPI.cpp
- Arduino_package/hardware/libraries/WS2812B/src/WS2812B.cpp
- Update WS2812B.cpp `show()` function
- Update SPI.cpp spelling error
> Update WS2812B.cpp to solve compilation error

- Arduino_package/hardware/libraries/WiFi/examples/ConnectWithWiFi/ConnectWithWEP/ConnectWithWEP.ino
- Arduino_package/hardware/libraries/WiFi/examples/ConnectWithWiFi/ConnectWithWPA/ConnectWithWPA.ino
- Arduino_package/hardware/libraries/WiFi/examples/WiFiAPMode/WiFiAPMode.ino
- Arduino_package/hardware/libraries/WiFi/src/WiFiClient.h
- Arduino_package/hardware/libraries/WiFi/src/WifiSerial.cpp
- Arduino_package/hardware/libraries/WiFi/src/WifiSerial.h
Added WifiSerial header and .cpp files
> Add read from Serial port feature to Wifi examples

- Arduino_package/hardware/cores/ambd/wifi_drv.cpp
- Arduino_package/hardware/cores/ambd/wifi_drv.h
- Arduino_package/hardware/cores/ambd/wl_definitions.h
- Arduino_package/hardware/libraries/WiFi/examples/ScanNetworks/ScanNetworks.ino
- Arduino_package/hardware/libraries/WiFi/src/WiFi.cpp
- Update wifi_drv to add in WPA3 encryption type checking
- Update wl_definition.h to add in WPA3 encryption mode
- Added WPA3 encryption type into scanNetworks.ino
- Amend spelling in WiFi.cpp
> Added WPA3 Encryption type for scan network example

- Arduino_package/hardware/libraries/Debugging/examples/ExampleDebug/ExampleDebug.ino
- Arduino_package/hardware/libraries/Debugging/examples/ExampleDebug/debug_custom.json
- Arduino_package/hardware/platform.txt
Fixed bugs when running example on Arduino IDE 2.0.2 and above
> Edited Debugging mode feature

- Arduino_package/package_realtek.com_amebad_early_index.json
Version 3.1.7 – 2023/05/09
Feature:
NA
API Updates:
- Add SPI API to support drawBitmap()
- Update "board.txt"
- Remove unnecessary "shield" check for Wi-Fi examples
Misc:
- Update IFTTT documentation to add in Line Notify features
> Pre Release Version 3.1.7

- Arduino_package/hardware/libraries/WS2812B/examples/WS2812B_Basics/WS2812B_Basics.ino
- Arduino_package/hardware/libraries/WS2812B/examples/WS2812B_Patterns/WS2812B_Patterns.ino
- Arduino_package/hardware/libraries/WS2812B/src/WS2812B.cpp
1. Add new variable TOTAL_NUM_OF_LED in constructor `led()` to allow full reset the WS2812B module.
2. Modify error message `printf()` function in WS2812B.cpp source code
Verification:
Verified on RTL8722DM EVB with `V3.1.7-build20230623` SDK
> Update WS2812B source code and examples

- Arduino_package/hardware/cores/ambd/ard_socket.c
- Arduino_package/hardware/cores/ambd/ard_socket.h
- Arduino_package/hardware/cores/ambd/server_drv.cpp
- Arduino_package/hardware/cores/ambd/server_drv.h
- Arduino_package/hardware/libraries/WiFi/examples/WiFiWebServer/WiFiWebServer.ino
- Arduino_package/hardware/libraries/WiFi/keywords.txt
- Arduino_package/hardware/libraries/WiFi/src/WiFiServer.cpp
- Arduino_package/hardware/libraries/WiFi/src/WiFiServer.h
- Add blocking mode API `setBlocking()` in WiFiServer.cpp
Verification:
Tested in Arduino 1&2 using AMB21/22
> Change WiFi server default socket connection to non-blocking mode

- Arduino_package/hardware/cores/ambd/amb_ard_pin_check.c
I2C Scanner hangs when reset for AMBD boards. Fix for 3.1.7-build20230921.
> Fix undefined behavior when doing pin_check

- Arduino_package/hardware/libraries/SPI/src/SPI.h
-----------
*eg.*
- Feature: Update SPI.h for compatability with U8G2 library etc.
- API Updates:
- Misc:
*eg.*
- BW16
- Windows 10
> Update SPI.h for compatibility with some libraries

- .github/workflows/CI_compile_examples.yml
- Arduino_package/hardware/libraries/WiFi/examples/ScanNetworksAdvanced/ScanNetworksAdvanced.ino
-----------
Adavanced example showing more information about the found WiFi Hotspots.
- BW16
- Windows 10
Please provide links to related issue, PRs etc. \
*eg.*
- Closes #215
> Advanced WiFi Scan Networks Example

- Arduino_package/hardware/libraries/OTA/src/OTA.cpp
-----------
*eg.*
- Feature: Bug fix for OTA by CSDN user. (https://blog.csdn.net/scream151/article/details/133453185)
- API Updates: 
- Misc:
*eg.*
- BW16
- Windows 10
> Bug Fix for OTA BW16, Fix is by CSDN user

- Arduino_package/hardware/libraries/WiFi/src/WiFiClient.cpp
*By completing this PR sufficiently, please help us to review and improve the quality of this PR and Release Notes*
1. [x] Please provide specific title that describe the change (*eg. Update Readme.md*)
2. [x] Please provide related links (*eg. This Pull Request is a fix of #issue_number*)
3. [x] Please **update the license/declaration** if applicable (*eg. Usage of other projects/apis/libs code*)
4. [x] Please check [Contributing guide](https://github.com/ambiot/ambd_arduino/blob/dev/CONTRIBUTING.md)
5. [x] Please **confirm option to "Allow edits and access to secrets by maintainers"** when opening a Pull Request
*This entire section above can be deleted if all items are checked.*
-----------
*eg.*
- Feature: Removed usage of …
> Removed usage of GOTO in WifiClient.cpp

- Arduino_package/hardware/libraries/FatfsSDIO/examples/read_html_from_SD_card/read_html_from_SD_card.ino
- Arduino_package/hardware/libraries/WiFi/examples/IPv6TCPServer/IPv6TCPServer.ino
- API Updates:
- replace Web_UI.html with Web_test.html
- add setBlockingMode
> Read HTML From SD Card Example Fix

- Arduino_package/hardware/libraries/Http/examples/SimpleHttpExample/SimpleHttpExample.ino
- API Updates: add set blocking mode to HTTP example
> Update HTTP example

- Arduino_package/hardware/libraries/SPI/src/SPI.cpp
- Arduino_package/hardware/libraries/SPI/src/SPI.h
- Arduino_package/hardware/libraries/Wire/src/Wire.cpp
- Arduino_package/hardware/libraries/Wire/src/Wire.h
*By completing this PR sufficiently, please help us to review and improve the quality of this PR and Release Notes*
-----------
*eg.*
- Feature: Datalogger (RTL8720DF)
- API Updates:
- Misc: i2c & spi application can be error
*eg.*
- Datalogger (RTL8720DF)
- ambd_arduino [V3.1.8-QC-V05](https://github.com/Ameba-AIoT/ameba-arduino-d/releases/tag/V3.1.8-QC-V05)
- Arduino IDE 2.3.0
- Windows 10
> Suggested addition: "|| defined(BOARD_DATALOGGER_AMB26)"

- Arduino_package/hardware/libraries/AudioCodec/examples/RecordPlaybackWav/RecordPlaybackWav.ino
- Arduino_package/hardware/libraries/AudioCodec/examples/RecordWavFile/RecordWavFile.ino
- Arduino_package/hardware/libraries/AudioCodec/src/AudioCodec.cpp
- Arduino_package/hardware/libraries/AudioCodec/src/AudioCodec.h
- API Updates: add API for PDM and input audio amplify
> Add PDM for Audio Record Example

- Arduino_package/hardware/libraries/WS2812B/src/WS2812B.h
*By completing this PR sufficiently, please help us to review and improve the quality of this PR and Release Notes*
-----------
*eg.*
- Feature: WS2812B
- Datalogger(RTL8720DF)
- ambd_arduino dev laster
- Arduino IDE 2.3.4
- Windows 10
> addition: "|| defined(BOARD_DATALOGGER_AMB26)"

- Arduino_package/hardware/libraries/MQTTClient/examples/LASS_Basic/LASS_Basic.ino
- API Updates:
add wifi client non-blocking mode
update to correct pin mapping
- AMB23
- ambd_arduino V3.1.8
- Arduino IDE 2.3.4
- Windows 10
> Update MQTT LASS_Basic example
