Ameba-AIoT/ameba-arduino-d

Arduino_package/hardware/libraries/WiFi/library.properties

When multiple libraries contain files matching an `#include` directive in the program, the Arduino build system must pick one to use for compilation. Multiple factors are used in order to make an intelligent determination of which library is best, as documented [here](https://arduino.github.io/arduino-cli/latest/sketch-build-process/#dependency-resolution).
In order to enhance this determination, the closeness of match between [the library.properties `name` value](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) and the filename in the `#include` directive is being added as one of those factors. This new factor is referred to as [**"Library Name Priority"**](https://arduino.github.io/arduino-cli/latest/sketch-build-process/#library-name-pri …

Use optimal bundled library name

---

Arduino_package/hardware/cores/arduino/wiring_digital.c

By observing the behavior with 328p, the INPUT behavior is set to "High Impedance", which acts the same as INPUT_PULLNONE in amebaD.
To match this, change INPUT_PULLNONE to INPUT.
Also, change currently INPUT to INPUT_PULLDOWN since its still useful.
Important: this might change many default behaviors, needs to test it fully or leave it untouched.

Change INPUT_PULLNONE to INPUT

---

Arduino_package/hardware/libraries/SPI/SPI.cpp

Modify return value of transfer16 function.

Modify transfer16 API

---

Arduino_package/hardware/libraries/WiFi/examples/ConnectWithWiFi/ConnectNoEncryption/ConnectNoEncryption.ino
Arduino_package/hardware/libraries/WiFi/examples/ConnectWithWiFi/ConnectWithWEP/ConnectWithWEP.ino
Arduino_package/hardware/libraries/WiFi/examples/ConnectWithWiFi/ConnectWithWPA/ConnectWithWPA.ino
Arduino_package/hardware/libraries/WiFi/examples/WiFiAPMode/WiFiAPMode.ino

add in examples for using UTF-8 encoding to connect to iPhone hotspots using non-ASCII SSID

Fix for iPhone hotspot SSIDs

---

Arduino_package/hardware/cores/ambd/main.cpp

Update line 117 RTOS priority from osPriorityRealtime decrease to osPriorityNormal.
Tested the following examples that this fix might not affect the function of other peripherals:
- Watchdog: “Watchdog Timer”
- WiFi: ” WiFiSSLClient “ 
- HTTP: "SimpleWebServerWiFi"
- MQTT: “MQTT_Basic”
- BLE: "BLE Scan"
- I2C: “LCD_HelloWorld”.
- SPI: "ILI9341_TFT_LCD_basic"
- UART: "Adafruit_GPS_parsing"

Update line117 osPriority in main.cpp to dev branch

---

Arduino_package/hardware/libraries/GPIO/examples/HCSR04_Ultrasonic/HCSR04_Ultrasonic.ino
Arduino_package/hardware/libraries/GPIO/examples/LED_InterruptCtrl/LED_InterruptCtrl.ino

- Change pin 13 to pin 11 for the following examples as BW16 does not have pin 13:
1. GPIO - Ultrasonic module
2. GPIO - LED interrupt control

Update GPIO pin number for GPIO examples

---

Arduino_package/hardware/cores/ambd/Arduino.h
Arduino_package/hardware/cores/ambd/ard_socket.c
Arduino_package/hardware/libraries/WiFi/src/WiFiClient.cpp

Add `lwip_fcntl(_sock, F_SETFL, O_NONBLOCK);` in `start_server()` and `start_server_v6()` to enable lwip non-blocking mode.
-------
**Thanks for Ameba Arduino user @jojoling's help with raising this bug and providing the solution.
Add in any code after WiFiWebServer.ino line 89: (For example: `Serial.println("abc");`)**
https://github.com/ambiot/ambd_arduino/blob/2e8a9df1f8a297cc643e858b42204908e391addf/Arduino_package/hardware/libraries/WiFi/examples/WiFiWebServer/WiFiWebServer.ino#L89
After the example is uploaded to the board and running, while no client is connecting to the Ameba board, the added line will never be able to be printed in the serial monitor. 
This is due to lwip's default running in "blocking" mode. Adding `lwip_fcntl(_sock, F_SETFL, O_NONBLOCK);` in `start_server()` …

Enable lwip non-blocking mode in ard_socket.c

---

Arduino_package/hardware/variants/awcu488_thingplus/variant.h

Some Arduino libraries use the SPI pins and simply name them "MOSI", "MISO", "SS", "SCK". These extra defines allow these to compile.

Added more SPI pin defines

---

Arduino_package/hardware/cores/ambd/wifi_drv.cpp
Arduino_package/hardware/cores/ambd/wifi_drv.h
Arduino_package/hardware/libraries/WiFi/src/WiFi.cpp

Modify typo in WiFi API:
- Update `getSSIDNetoworks` to `getSSIDNetworks`
- Update `getRSSINetoworks` to `getRSSINetworks`

Modify typo in WiFi API

---

Arduino_package/hardware/variants/awcu488_thingplus/variant.h
Arduino_package/hardware/variants/rtl8720dn_bw16/variant.h
Arduino_package/hardware/variants/rtl8722dm/variant.h
Arduino_package/hardware/variants/rtl8722dm_mini/variant.h

- Fix compilation error with issue (#131)
- Update variant.h in all boards to add a missing macro
Verification:
- Tested against WiFiSSLClient and Blink example and passed

Fix issue (#131) - part 2 - add missing macro to improve compatibility

---

Arduino_package/hardware/platform.txt

This patch enables use of Arduino libraries that contain precompiled binaries.
More information on this Arduino Library feature can be found on: https://arduino.github.io/arduino-cli/0.27/library-specification/#precompiled-binaries

Enable precompiled libraries

---

Arduino_package/hardware/libraries/SPI/examples/ILI9341_TFT_LCD_PM2.5/ILI9341_TFT_LCD_PM2.5.ino

- Amend default SPI_BUS in ILI9341_TFT_LCD_PM2.5.ino to SPI instead of SPI0

Update TFT LCD example SPI_BUS

---

Arduino_package/hardware/libraries/PowerSave/examples/TicklessMode/TicklessMode.ino

1. Fixed mirror `printf()` typo and log mismatch with online documentation
Verification:
Verified on RTL8722DM EVB with `V3.1.7` SDK

Update Power Save TicklessMode example

---

Arduino_package/hardware/cores/ambd/wiring_analog.c
Arduino_package/hardware/cores/ambd/wiring_analog.h

- Add analogSet() function
- Change from int to float for gain, offset, ret and mv
- Modify analogRead function

Update wiring_analog 

---

Arduino_package/hardware/cores/ambd/server_drv.cpp
Arduino_package/hardware/libraries/WiFi/examples/WiFiWebServer/WiFiWebServer.ino
Arduino_package/hardware/libraries/WiFi/src/WiFi.cpp
Arduino_package/hardware/libraries/WiFi/src/WiFi.h
Arduino_package/hardware/libraries/WiFi/src/WiFiClient.cpp
Arduino_package/hardware/libraries/WiFi/src/WiFiClient.h
Arduino_package/hardware/libraries/WiFi/src/WiFiSSLClient.cpp
Arduino_package/hardware/libraries/WiFi/src/WiFiSSLClient.h
Arduino_package/hardware/libraries/WiFi/src/WiFiServer.cpp
Arduino_package/hardware/libraries/WiFi/src/WiFiServer.h
Arduino_package/hardware/libraries/WiFi/src/WiFiUdp.cpp
Arduino_package/hardware/libraries/WiFi/src/WiFiUdp.h

- Added destructor for `WiFi()`, `WiFiClient()`, `WiFiSSLClient()`, `WiFiServer()`, `UDP()` Class
- Modified [WiFiWebServer.ino](https://github.com/ambiot/ambd_arduino/compare/dev...S10143806H:ambd_arduino:dev#diff-204ffc57b37a3b16f6a4398a936bb3624e8e2cdf9219ed46f36b3fcf37453be9) `printf()` sequence and structure to ensure the destructor of `WiFiClient()` takes into affect
- Added `printf()` information for future debugging
Verification:
Verified on BW16 with ARDUINO IDE1

Add in destructors for all Wi-Fi Classes

---

Arduino_package/hardware/cores/ambd/ard_socket.c

- Update `send_data()` API to be able to handle TCP packet in the size of `TCP_MSS` predefined in lwip
- Add error handles in `send_data()` if receive failed
Verification:
Verified using BW16 on Arduino IDE1

Update send_data() in ard_socket.c

---

Arduino_package/hardware/boards.txt
Arduino_package/hardware/cores/ambd/Arduino.h
Arduino_package/hardware/cores/ambd/ard_socket.c
Arduino_package/hardware/cores/ambd/wiring_constants.h

- support standard lib `<string>` by default, default enable `Arduino_STD_PRINTF` that allows `printf()` and `_rtl_printf()` simultaneously
- include `-DArduino_STD_PRINTF` in extra-flag
- modify the define sequence of `min()` `max()` in `wiring_constants.h` to remove compilation error
- ensures downward compatibility
- remove extra `printf()` debug message in `ard_socket.c`
Verification:
Verified on Arduino IDE1&2 with Ameba D series: AMB21/22/23/25/26 BW16/BW16TypeC AWCU488 and u-blox NORA-W30

Support c++ standard lib by default

---

Arduino_package/hardware/cores/ambd/amb_ard_pin_check.c
Arduino_package/hardware/cores/ambd/wiring_digital.c

- enhance the logic of checking
- speed up the process
- BW16-TypeC
- ambd_arduino Version 3.1.7 – 2023/11/30
- arduino IDE 2.3.0
- windows 10

Update the pin_check related

---

Arduino_package/hardware/libraries/GPIO/examples/BW16_RGB_LED/BW16_RGB_LED.ino

Example on how to Blink and Fade the RGB LED on the BW16.
It is a simple sketch showing what can be done with the RGB LED.
Tested on a BW16-TypeC with Arduino IDE 2.3.0 in Windows 10.

Create example for the RGB LED on the BW16

---

Arduino_package/hardware/cores/ambd/Udp.h

This brings the Udp.h from Arduino to ambd
Source: https://github.com/arduino/ArduinoCore-avr/blob/master/cores/arduino/Udp.h
(this exact file is also used on ESP32/Teensy and other cores:
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/Udp.h  
https://github.com/PaulStoffregen/cores/blob/master/teensy4/Udp.h
)
To be tested with Ethernet shield, for example: https://docs.arduino.cc/tutorials/ethernet-shield-rev2/web-server/
Fixes: https://github.com/ambiot/ambd_arduino/issues/229

Create Udp.h to fix Ethernet Lib issue

---

Arduino_package/hardware/cores/ambd/wiring_constants.h

- Modify wiring_constant.h to resolve min not declared when Arduino_STD_PRINTF is enabled
- BW16
- Windows 10
- https://github.com/ambiot/ambd_arduino/issues/231

Solve SPI compile issues when Arduino_STD_PRINTF enabled

---

Arduino_package/hardware/variants/datalogger_amb26/variant.cpp
Arduino_package/hardware/variants/datalogger_amb26/variant.h

*By completing this PR sufficiently, please help us to review and improve the quality of this PR and Release Notes*
-----------
- Misc:
Adjust the pin definitions
- Datalogger iot Board /AMB26
- Windows 10

Adjust the pin definitions for the hardware section of the Datalogger board.

---

Arduino_package/hardware/libraries/WS2812B/src/WS2812B.cpp

- removed disabling of SPI in show()
- Note, we need SPI to stay open for any repeat calls to show().
-----------
This allows the user to call show() more than once, allowing the WS2812B LED to change colors throughout the sketch.
- Feature: multiple calls to show() to adjust WS2812B LED
- API Updates: show()
- SparkFun Thing Plus NORAW306
- ambd_arduino V3.1.8
- Windows 11
- fixes issue #241

Remove disabling of SPI in show()

---

Arduino_package/hardware/libraries/SPI/src/SPI.cpp

Arduino libraries should update SPI settings when beginTransaction() is called with a complete struct of SPISettings is passed in as an argument.
- Feature: SPI
- API Updates: beginTransaction()
- Hardware: Sparkfun NoraW306
- ambd_arduino V3.1.8
- Windows 11
This PR fixes issue #239

Updating dataMode in beginTransaction()

---

Arduino_package/hardware/libraries/SoftwareSerial/src/SoftwareSerial.cpp

fix SoftwareSerial::setBufferSize use realloc without change _receive_buffer point.
- BW16
- Windows 11

fix SoftwareSerial::setBufferSize realloc

---

Arduino_package/hardware/libraries/PowerSave/src/PowerSave.cpp

- Feature: Bug fix for deepsleep examples compilation error
- API Updates: NA
- Misc: NA
Environment:
- AMB23
- ambd_arduino V3.1.8-build20241128
- Ubuntu

Fix for Deepsleep examples compilation error

---

.github/workflows/CI_compile_examples.yml
Arduino_package/hardware/libraries/SPI/examples/BW16_SD_Card_SPI/BW16_SD_Card_SPI.ino
Arduino_package/hardware/variants/rtl8720dn_bw16/variant.h

Add BW16 SD Card Example using the SPI Bus

---

Arduino_package/hardware/libraries/BLE/src/BLERemoteCharacteristic.cpp
Arduino_package/hardware/libraries/BLE/src/BLERemoteCharacteristic.h

In BLECharacteristic, we already have setWriteProperty() and setWriteNRProperty().
But the coresponded BLERemoteCharacteristic can only send data to when setWriteProperty() is used.
According to "profile_client.h", there are GATT_WRITE_TYPE_REQ and GATT_WRITE_TYPE_CMD that can distinguish these two.
Modify BLERemoteCharacteristic.h and BLERemoteCharacteristic.cpp to add this function.

Send data with NO RESPONSE on BLERemoteCharacteristic
